{'Learning_rate': 0.01, 'epochs': 50, 'batch_size': 32, 'layer_size': [784, 128, 64, 10]}
50
epoch: 0, train_loss:1.3827, val_accuracy: 0.7220
epoch: 1, train_loss:0.8293, val_accuracy: 0.7559
epoch: 2, train_loss:0.7013, val_accuracy: 0.7773
epoch: 3, train_loss:0.6419, val_accuracy: 0.7851
epoch: 4, train_loss:0.6144, val_accuracy: 0.8019
epoch: 5, train_loss:0.6040, val_accuracy: 0.7850
epoch: 6, train_loss:0.5899, val_accuracy: 0.7879
epoch: 7, train_loss:0.5882, val_accuracy: 0.7915
epoch: 8, train_loss:0.5847, val_accuracy: 0.7870
epoch: 9, train_loss:0.6019, val_accuracy: 0.7920
epoch: 10, train_loss:0.5911, val_accuracy: 0.7986
epoch: 11, train_loss:0.5903, val_accuracy: 0.7937
epoch: 12, train_loss:0.5926, val_accuracy: 0.7664
epoch: 13, train_loss:0.5922, val_accuracy: 0.7874
epoch: 14, train_loss:0.6035, val_accuracy: 0.7781
epoch: 15, train_loss:0.6069, val_accuracy: 0.7918
epoch: 16, train_loss:0.6020, val_accuracy: 0.7969
epoch: 17, train_loss:0.5970, val_accuracy: 0.7989
epoch: 18, train_loss:0.5936, val_accuracy: 0.7689
epoch: 19, train_loss:0.5932, val_accuracy: 0.7899
epoch: 20, train_loss:0.5964, val_accuracy: 0.7915
{'Learning_rate': 0.01, 'epochs': 50, 'batch_size': 32, 'layer_size': [784, 128, 64, 10]}
{'Learning_rate': 0.01, 'epochs': 50, 'batch_size': 32, 'layer_size': [784, 128, 64, 10]}
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wandb in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (0.19.7)
Requirement already satisfied: click!=8.0.0,>=7.1 in c:\anaconda3\lib\site-packages (from wandb) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in c:\anaconda3\lib\site-packages (from wandb) (3.1.43)
Requirement already satisfied: platformdirs in c:\anaconda3\lib\site-packages (from wandb) (3.10.0)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in c:\anaconda3\lib\site-packages (from wandb) (4.25.3)
Requirement already satisfied: psutil>=5.0.0 in c:\anaconda3\lib\site-packages (from wandb) (5.9.0)
Requirement already satisfied: pydantic<3,>=2.6 in c:\anaconda3\lib\site-packages (from wandb) (2.8.2)
Requirement already satisfied: pyyaml in c:\anaconda3\lib\site-packages (from wandb) (6.0.1)
Requirement already satisfied: requests<3,>=2.0.0 in c:\anaconda3\lib\site-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (from wandb) (2.22.0)
Requirement already satisfied: setproctitle in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (from wandb) (1.3.5)
Requirement already satisfied: setuptools in c:\anaconda3\lib\site-packages (from wandb) (75.1.0)
Requirement already satisfied: colorama in c:\anaconda3\lib\site-packages (from click!=8.0.0,>=7.1->wandb) (0.4.6)
Requirement already satisfied: six>=1.4.0 in c:\anaconda3\lib\site-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\anaconda3\lib\site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.7)
Requirement already satisfied: annotated-types>=0.4.0 in c:\anaconda3\lib\site-packages (from pydantic<3,>=2.6->wandb) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\anaconda3\lib\site-packages (from pydantic<3,>=2.6->wandb) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\anaconda3\lib\site-packages (from pydantic<3,>=2.6->wandb) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (2024.8.30)
wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
Requirement already satisfied: smmap<5,>=3.0.1 in c:\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (4.0.0)
